# Requires a tart vm with xcode-select and node 18.15.0 installed
# Run this with cirrus run --dirty. This will mount the current volume with read write

run_dev_task:
  macos_instance:
    image: codify-test-vm
    port: 9226:9226
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package-lock.json
    populate_script: npm ci
  run_script:
    - sleep 2000

integration_test_dev_macos_task:
  macos_instance:
    image: codify-test-vm
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package-lock.json
    populate_script: npm ci
  test_script:
    - npm run test:integration -- --disable-console-intercept $DEBUG --no-file-parallelism

integration_test_dev_linux_task:
  arm_container:
    image: kevinwang5658/codify-test-linux:latest
#  node_modules_cache:
#    folder: node_modules
#    fingerprint_script: cat package-lock.json
#    populate_script: npm ci
  test_script:
    - adduser --disabled-password --gecos '' newuser
    - su - newuser
    - npm ci
    - npm run test:integration -- --disable-console-intercept $DEBUG --no-file-parallelism

integration_individual_test_macos_task:
  macos_instance:
    image: codify-test-vm
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package-lock.json
    populate_script: npm ci
  test_script:
    - echo $FILE_NAME
    - npm run test -- $FILE_NAME --disable-console-intercept $DEBUG --no-file-parallelism

integration_individual_test_linux_task:
  arm_container:
    image: kevinwang5658/codify-test-linux:latest
#  node_modules_cache:
#    folder: node_modules
#    fingerprint_script: cat package-lock.json
#    populate_script: npm ci
  test_script:
    - chown -R node /tmp/cirrus-ci/working-dir
    - su node -c "npm install"
    - echo $FILE_NAME
    - su node -c "npm run test -- $FILE_NAME --disable-console-intercept $DEBUG --no-file-parallelism"
