# Requires a tart vm with xcode-select and node 18.15.0 installed
# Run this with cirrus run --dirty. This will mount the current volume with read write

run_dev_task:
  macos_instance:
    image: codify-test-vm
  run_script:
    - sleep 2000

integration_test_dev_task:
  macos_instance:
    image: codify-test-vm
  test_script:
    - npm run test:integration

integration_individual_test_task:
  macos_instance:
    image: codify-test-vm
  test_script:
    - echo $FILE_NAME
    - npm run test -- $FILE_NAME
