# Requires a tart vm with xcode-select and node 18.15.0 installed
# Run this with cirrus run --dirty. This will mount the current volume with read write

run_dev_task:
  macos_instance:
    image: sonoma-vm
  run_script:
    - sleep 2000

integration_test_dev_task:
  macos_instance:
    image: sonoma-vm
  test_script:
    - source ~/.nvm/nvm.sh
    - npm run test:integration
