#!/bin/bash

tart run codify-sonoma --dir . --no-graphics &

sleep 2

echo "Started tart vm"
tart ip codify-sonoma

sleep 10

if [ -d .Trashes ]; then
  echo "Found .Trashes folder generated by Tart. Deleting... Not deleting this will lead to run time issues."
  sudo rm -rf .Trashes
fi

if [ -d .fseventsd ]; then
  echo "Found .fseventsd folder generated by Tart. Deleting... Not deleting this will lead to run time issues."
  sudo rm -rf .fseventsd
fi

# keep this script running indefinitely
tail -f /dev/null

# Kill the vm (child process) when this script ends
trap "tart stop codify-sonoma" EXIT
